## Students Information

Please enter the names and IDs of the two students below:

1. **Name**: Abdelrahman Hamdy Ahmed  
   **ID**: `9202833` 

2. **Name**: Abdelrahman Noaman Loqman  
   **ID**: `9202851` 


## Students Instructions

This is your first graded lab assignment, as you put the work you have studied in the lectures in action, please take this opportunity to enhance your understanding of the concepts and hone your skills. As you work on your assignment, please keep the following instructions in mind:

- Clearly state your personal information where indicated.
- Be ready with your work before the time of the next discussion slot in the schedule.
- Plagiarism will be met with penalties, refrain from copying any answers to make the most out of the assignment. If any signs of plagiarism are detected, actions will be taken.
- It is acceptable to share the workload of the assignment bearing the discussion in mind.
- Feel free to [reach out](mailto:cmpsy27@gmail.com) if there were any ambiguities or post on the classroom.

## Submission Instructions

To ensure a smooth evaluation process, please follow these steps for submitting your work:

1. **Prepare Your Submission:** Alongside your main notebook, include any additional files that are necessary for running the notebook successfully. This might include data files, images, or supplementary scripts.

2. **Rename Your Files:** Before submission, please rename your notebook to reflect the IDs of the two students working on this project. The format should be `ID1_ID2`, where `ID1` and `ID2` are the student IDs. For example, if the student IDs are `9123456` and `9876543`, then your notebook should be named `9123456_9876543.ipynb`.

3. **Check for Completeness:** Ensure that all required tasks are completed and that the notebook runs from start to finish without errors. This step is crucial for a smooth evaluation.

4. **Submit Your Work:** Once everything is in order, submit your notebook and any additional files via the designated submission link on Google Classroom **(code: 2yj6e24)**. Make sure you meet the submission deadline to avoid any late penalties.
5. Please, note that the same student should submit the assignments for the pair throughout the semester.

By following these instructions carefully, you help us in evaluating your work efficiently and fairly **and any failure to adhere to these guidelines can affect your grades**. If you encounter any difficulties or have questions about the submission process, please reach out as soon as possible.

We look forward to seeing your completed projects and wish you the best of luck!





## Installation Instructions

In this lab assignment, we require additional Python libraries for scientific mathematics, particularly in the context of machine learning (ML) and satellite image analysis. To fulfill these requirements, we need to install Scikit-learn and Scikit-image. 
1. Install Scikit-learn  
Scikit-learn (Sklearn) is a powerful Python library for ML tasks, offering various algorithms for classification, regression, clustering, and model evaluation. It is extensively used for analyzing satellite imagery, enabling tasks such as land cover classification and environmental parameter prediction. On the other hand, Scikit-image (Skimage) provides comprehensive tools for image processing and computer vision, facilitating tasks such as image preprocessing, feature extraction, and segmentation. These libraries are essential for extracting valuable insights from satellite images and conducting advanced analysis in scientific computing and research domains.
```bash
pip install scikit-learn scikit-image
```


> **Note:** You are allowed to install any other necessary libraries you deem useful for solving the lab. Please ensure that any additional libraries are compatible with the project requirements and are properly documented in your submission.


## Maximum Likelihood Estimator (MLE) Classifier
The Maximum Likelihood Estimator (MLE) is a fundamental statistical approach used to infer the parameters of a given distribution that are most likely to result in the observed data. In the context of image classification, MLE helps to quantify the probability of observing the data within each predefined class based on their distinct statistical properties. This method is highly effective for classifying images into categories by comparing the likelihoods of the data under different model parameters, enabling the most probable class assignment.

1. **Calculate Class Priors**: Estimate the probability of each class based on the training dataset. This is expressed as:
   $$
   P(C_k) = \frac{N_k}{N}
   $$
   where \(N_k\) is the number of samples of class \(k\) and \(N\) is the total number of samples.

2. **Estimate Class-specific Parameters**: For each class, estimate parameters such as the mean \(\mu_k\) and covariance \(\Sigma_k\) of features that describe the distribution of the data:
   $$
   \mu_k = \frac{1}{N_k} \sum_{x \in C_k} x
   $$
   $$
   \Sigma_k = \frac{1}{N_k} \sum_{x \in C_k} (x - \mu_k)(x - \mu_k)^T
   $$

3. **Compute Likelihoods**: For a given test instance \(x\), compute the likelihood of that instance belonging to each class using the estimated parameters:
   $$
   p(x | C_k) = \frac{1}{(2\pi)^{d/2} |\Sigma_k|^{1/2}} \exp\left(-\frac{1}{2} (x - \mu_k)^T \Sigma_k^{-1} (x - \mu_k)\right)
   $$

4. **Classify Based on Maximum Likelihood**: Assign the class label to each test instance based on the highest likelihood, which can be calculated as:
   $$
   \hat{y} = \arg\max_{k} P(C_k) \cdot p(x | C_k)
   $$

The Naive Bayes classifier is perhaps the most well-known application of the Maximum Likelihood Estimator principle in classification tasks. It assumes that the features in each class are independent, simplifying the computation of likelihoods. While Naive Bayes is popular for its simplicity and efficiency, it is not the only technique that leverages the MLE approach. Other classical alternatives include Logistic Regression, which applies MLE to estimate the parameters that best predict categorical outcomes, and Gaussian Mixture Models, which use MLE to estimate the parameters of multiple Gaussian distributions within the data. Students are encouraged to explore these models to gain a deeper understanding of statistical estimation techniques.


## Req- Image Classification for EuroSATallBands
Image classification is a key challenge in satellite imaging and remote sensing. As discussed in the lecture, this task is typically conducted on a pixel-wise basis because a single image can contain multiple textural elements of different celestial features. However, for this specific assignment, we will focus on identifying the dominant phenomena in the image as the basis for classification.

- **Load the Images**: Load the images of the EuroSAT dataset that belong to the **residential**, **river**, and **forest** classes.

- **Split the Dataset**: Split the dataset such that 10% of each class is used as testing data, and the remainder is used for training your classifier. Use the indices provided by `np.random.choice` with seed set to `27`. **Code is provided do not change it**.

- **Feature Extraction**: Extract suitable features from the images that you think might be relevant in distinguishing each class from the others. Keep in mind the curse of dimensionality when selecting features.

- **Implement a Maximum Likelihood Estimator (MLE)**: Implement a Maximum Likelihood Estimator (MLE) based on your training data. 
- **Report Accuracy and Average F1 Score**: After testing your classifier on the test set, report the **Accuracy** and **Average F1 Score** of your model.


In [1]:
# Add your libraries here
import numpy as np
import os
from skimage import io
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, recall_score, precision_score

In [2]:
# DO NOT CHANGE THIS CELL
## Training set indices.
np.random.seed(27)  # Set random seed for reproducibility

# Randomly select indices for the test sets for each class
residential_test_indices = np.random.choice(np.arange(3000), size=300, replace=False)
forest_test_indices = np.random.choice(np.arange(3000), size=300, replace=False)
river_test_indices = np.random.choice(np.arange(2500), size=250, replace=False)


In [3]:
# 1. Load the Images
data_dir = "EuroSATallBands/ds/images/remote_sensing/otherDatasets/sentinel_2/tif"
classes = ["residential", "river", "forest"]
class_labels = []
x = [[] for _ in range(len(classes))]
y = [[] for _ in range(len(classes))]
for i, cls in enumerate(classes):
    class_labels.append(i)
    class_dir = os.path.join(data_dir, cls)
    for img_name in os.listdir(class_dir):
        img = io.imread(os.path.join(class_dir, img_name))
        x[i].append(img)
        y[i].append(i)

In [4]:
# 2. Split the Dataset
X_train, X_test, Y_train, Y_test = [], [], [], []
for i, indices in enumerate([residential_test_indices, river_test_indices, forest_test_indices]):
    x[i] = np.array(x[i])
    y[i] = np.array(y[i])
    X_train.append(np.delete(x[i], indices, axis=0))
    Y_train.append(np.delete(y[i], indices, axis=0))
    X_test.append(x[i][indices])
    Y_test.append(y[i][indices])
x_train = np.concatenate(X_train)
y_train = np.concatenate(Y_train)
x_test = np.concatenate(X_test)
y_test = np.concatenate(Y_test)
print(f"Training Set: {len(y_train)} samples")
print(f"Test Set: {len(y_test)} samples")
print(f"Training Set Shape: {x_train.shape}")
print(f"Test Set Shape: {x_test.shape}")

Training Set: 7650 samples
Test Set: 850 samples
Training Set Shape: (7650, 64, 64, 13)
Test Set Shape: (850, 64, 64, 13)


In [21]:
# 3. Feature Extraction
x_train_features = np.std(x_train, axis=(1, 2)) / np.mean(x_train, axis=(1, 2))
x_test_features = np.std(x_test, axis=(1, 2)) / np.mean(x_test, axis=(1, 2))
print(f"Training Set Features Shape: {x_train_features.shape}")

Training Set Features Shape: (7650, 13)


In [9]:
# 4. Maximum Likelihood Estimator
class MLE:
    def __init__(self):
        self.class_means = None
        self.class_covs = None
        self.class_priors = None

    def fit(self, x_train, y_train):
        self.class_means = np.array([np.mean(x_train[y_train == i], axis=0) for i in range(len(classes))])
        self.class_covs = np.array([np.cov(x_train[y_train == i], rowvar=False) for i in range(len(classes))])
        self.class_priors = np.array([np.mean(y_train == i) for i in range(len(classes))])

    def predict(self, x_test):
        probs = np.array([np.exp(-0.5 * np.sum((x_test - self.class_means[i]) @ np.linalg.inv(self.class_covs[i]) * (x_test - self.class_means[i]), axis=1)) / np.sqrt(np.linalg.det(self.class_covs[i])) for i in range(len(classes))]).T
        probs = probs * self.class_priors
        return np.argmax(probs, axis=1)

In [22]:
# 5. Evaluation
mle = MLE()
mle.fit(x_train_features, y_train)
y_pred = mle.predict(x_test_features)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="macro", zero_division=0, labels=class_labels)
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred, labels=class_labels)}")
print(f"Recall: {recall_score(y_test, y_pred, average='macro', zero_division=0, labels=class_labels):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='macro', zero_division=0 ,labels=class_labels):.4f}")
print(f"F1 Score: {f1:.4f}")
print("---------------------")
print(f"Accuracy: {accuracy * 100:.2f}%")

---------------------
Confusion Matrix:
[[294   6   0]
 [  3 245   2]
 [  4   3 293]]
Recall: 0.9789
Precision: 0.9782
F1 Score: 0.9785
---------------------
Accuracy: 97.88%


### Grading Rubric (Total: 10 Marks)

The lab is graded based on the following criteria:

1. **Data Loading and Preparation (2 Marks)**
   - Correctly loads images for the residential, river, and forest classes. (0.5 Marks)
   - Accurately splits the dataset into training and testing subsets and clearly shows this split. (1.5 Marks)

2. **Feature Extraction (2 Marks)**
   - Implements feature extraction appropriately, considering the curse of dimensionality. (1 Mark)
   - Extracts and justifies the selection of features relevant to distinguishing the classes. (1 Mark)

3. **Implementation of MLE Classifier (3 Marks)**
   - Correctly calculates and clearly shows class priors and class-specific parameters. (1 Mark)
   - Accurately computes likelihoods using the likelihood equation (probability density function) and classifies based on maximum likelihood. Must clearly show these calculations and explain the choice of likelihood equation. (2 Marks)

4. **Model Evaluation and Understanding (3 Marks)**
   - Shows **confusion matrix** and correctly calculates and clearly shows the calculations for Accuracy and Average F1 Score. (1 Mark)
   - **Comparison amongst your peers.** Compares the model's performance against those of peers to identify strengths and areas for improvement. (2 Marks)

Each section of the lab will be evaluated on completeness, and correctness in approach and analysis. Part of the rubric also includes the student's ability to explain and justify their choices and results.


## Submission Instructions

To ensure a smooth evaluation process, please follow these steps for submitting your work:

1. **Prepare Your Submission:** Alongside your main notebook, include any additional files that are necessary for running the notebook successfully. This might include data files, images, or supplementary scripts.

2. **Rename Your Files:** Before submission, please rename your notebook to reflect the IDs of the two students working on this project. The format should be `ID1_ID2`, where `ID1` and `ID2` are the student IDs. For example, if the student IDs are `9123456` and `9876543`, then your notebook should be named `9123456_9876543.ipynb`.

3. **Check for Completeness:** Ensure that all required tasks are completed and that the notebook runs from start to finish without errors. This step is crucial for a smooth evaluation.

4. **Submit Your Work:** Once everything is in order, submit your notebook and any additional files via the designated submission link on Google Classroom **(code: 2yj6e24)**. Make sure you meet the submission deadline to avoid any late penalties.
5. Please, note that the same student should submit the assignments for the pair throughout the semester.

By following these instructions carefully, you help us in evaluating your work efficiently and fairly **and any failure to adhere to these guidelines can affect your grades**. If you encounter any difficulties or have questions about the submission process, please reach out as soon as possible.

We look forward to seeing your completed projects and wish you the best of luck!
